base/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('hauts/', views.hauts, name='hauts'),
    path('robes/', views.robes, name='robes'),
    path('pantalons/', views.pantalons, name='pantalon'),
    path('jupes/', views.jupes, name='jupes'),
    path('contact/', views.contact, name='contact'),
    
    
]

cart/urls.py
from django.urls import path
from . import views
app_name= 'cart'

urlpatterns= [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name= 'cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name= 'cart_remove'),
 	path('checkout/', views.CheckoutView.as_view(), name='checkout'),
	# path('checkout/', views.checkout, name='checkout'),
	path('confirmation/', views.confirmation, name='confirmation'),
	path('paysuccess/', views.paysuccess, name='paysuccess'),
 
 
]

fripeproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('onlineshop/', include('onlineshop.urls', namespace='onlineshop')),
    path('', include('base.urls')),
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/urls.py
from django.urls import path
from . import views

app_name= 'onlineshop'

urlpatterns = [
    path('product_list', views.product_list, name= 'product_list'),
    path('<slug:category_slug>/', views.product_list, name= 'product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name= 'product_detail'),
]

cart/models.py
from django.db import models
from onlineshop.models import Product


class OrderItem(models.Model):
    item=models.ManyToManyField(Product)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return f"{self.quantity} de {self.item.name} "
    
    
class Paiements(models.Model):
    idd=models.BigAutoField(primary_key=True)
    numero = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    adresse = models.CharField(max_length=200)
    # items=models.OneToOneField(OrderItem,on_delete=models.CASCADE,default=1)
    items = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
    ordered_date=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        # ordering = ('idd',)
        verbose_name_plural = 'paiements'

    def __str__(self):
        # return str(self.idd)
        return str(self.numero)
    
    def get_num(self):
        return self.numero
    
    def get_paymentid(self):
        return self.idd

    
    def get_adr(self):
        return self.adresse
    
    def set_ord(self, ordered):
        self.ordered=ordered
        return self.ordered
    

cart/forms.py
from django import forms
from .models import Paiements

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]
class CartAddProductForm(forms.Form):
	quantity= forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	override= forms.BooleanField( required=False, initial=False, widget = forms.HiddenInput)
    

class PaymForm(forms.Form):
    numero = forms.CharField()
    adresse = forms.CharField()

cart/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .cart import Cart
from django.views.decorators.http import require_POST
from onlineshop.models import Product
from .models import Paiements,OrderItem
from .forms import CartAddProductForm
from django.views.generic import View
from .forms import PaymForm
import requests
from django.contrib import messages
from django.contrib.auth.models import User
import json
from django.utils import timezone



@require_POST
def cart_add(request, product_id): 
    cart= Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form =CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product, quantity = cd['quantity'], overrride_quantity = cd['override']) 
        order_item, created= OrderItem.objects.get_or_create(request, ordered=False)
        # order_item, created= OrderItem.objects.add(item=product, ordered=False)
        order_item.item.add(product)
        order_item.save()
        # order_qs=Paiements.objects.create(items=order_item,ordered=False)
        # paiements, created = Paiements.objects.get_or_create(items=order_item, ordered=False)
        paiements = Paiements.objects.filter(items=order_item).first()
        paiements.save()
        return redirect('cart:cart_detail')
        # if order_qs.exists():
        #     order=order_qs[0]
        #     if order.items.filter(item__slug=product.slug).exists():
        #         order_item.quantity=1
        #         order_item.save()
        #         messages.success(request, f"{product.name}'s quantity was updated ")
        #         return redirect('cart:cart_detail')
        #     else:
        #         order.items.add(order_item)
        #         # order.items.set([order_item])
        #         # order.items.add()
        #         order.save()
        #         messages.success(request, f"{product.name} was added to your cart")
        #         return redirect('cart:cart_detail')
        # else:
        #     ordered_date=timezone.now()
        #     order=Paiements.objects.create(request, ordered=False,ordered_date=ordered_date)
        #     order.items.add(order_item)
        #     # order.items.set([order_item])
            
        #     # order.items.add()
        #     order.save()
        #     messages.success(request, f"{product.name} was added to your cart")
        #     return redirect('cart:cart_detail')
        
	# return redirect('cart:cart_detail')
	
def cart_remove(request, product_id):
	cart= Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart= Cart(request)
	for item in cart:
		item['update_quantity_form']= CartAddProductForm(initial=
                                                        {'quantity':item['quantity'], 'override':True})
	return render(request, 'cart/detail.html', {'cart': cart})


import random

def generate_id():
    """Generate a unique ID of at least 4 digits"""
    with open("used_ids.txt", "r") as f:
        used_ids = set(f.read().split("\n"))

    while True:
        # Generate a random integer between 1000 and 9999
        new_id = random.randint(1000, 9999)
        if new_id not in used_ids:
            break

    with open("used_ids.txt", "a") as f:
        f.write(str(new_id) + "\n")

    yield new_id
class CheckoutView(View):
    def get(self, *args, **kwargs):
        cart= Cart(self.request)
        for item in cart:
            item['update_quantity_form']= CartAddProductForm(initial=
                                                        {'quantity':item['quantity'], 'override':True})
            return render(self.request, 'cart/checkout.html', {'cart': cart}) 

    
    def post(self, *args, **kwargs):
        authentication_classes = []
        form = PaymForm(self.request.POST or None)
        order_item= OrderItem.objects.filter( ordered=False)
        
        payment=Paiements.objects.filter(ordered=False, items__in=order_item)
        if form.is_valid():  
            numero = form.cleaned_data.get('numero')
            adresse = form.cleaned_data.get('adresse')
            payment=payment.first()
            id_generator = generate_id()
            payment.idd= next(id_generator)
            
            payment.numero = numero
            payment.adresse = adresse
            payment.save()
            # pay = Paiements(
            #         numero=numero,
            #     	adresse=adresse,
            #     )
            # orderItems = OrderItem(
            #         numero =numero,	
            #     )
            
            # orderItems.save()
            
                
            return redirect('cart:confirmation')

        else:
            print('form is invalid')
            return redirect('cart:checkout')
        
def confirmation(request):
    
    cart= Cart(request)
    for item in cart:
            item['update_quantity_form']= CartAddProductForm(initial=
                                                        {'quantity':item['quantity'], 'override':True})
   
    paymentidd=Paiements.objects.latest('idd').get_paymentid()
    
    numero =Paiements.objects.last()
    context = {
                'cart': cart,
                'paymentidd':paymentidd,
                'numero':numero
            }
    return render(request,'cart/confirmation.html',context)
        
def status(status):
    types={'0': 'Paiement réussi avec succès', '2' : 'En cours', '4': 'Expiré', '6': 'Annulé'}
    return types[str(status)]
    

def paysuccess(request):
    url ='https://paygateglobal.com/api/v2/status'
    
    identifier=Paiements.objects.latest('idd').get_paymentid()  
    params = dict(
					auth_token='593bd3ea-c9ae-4bc3-bb7b-d92cfaba604b',
					identifier= identifier,
				)
    res = requests.post(url,params=params)
    ct =res.json()
    st=status(ct['status'])
    if st=='Paiement réussi avec succès':
        print(st)
        numero =Paiements.objects.last()
        numero.ordered=True
        numero.save() 
        return render(request,'cart/paysucess.html')
    elif st=='En cours':
         print(st)
         messages.info(request, " veuillez valider sur votre téléphone portable")
         return redirect('cart:checkout')
    elif st=='Expiré':
         print(st)
         messages.info(request, " Etat de votre paiement: Expiré; veuillez recommencer")
         return redirect('cart:checkout')
    elif st=='Annulé':
         print(st)
         messages.info(request, "Vous avez annulé votre commande")
         return redirect('cart:checkout')
    else:
        return redirect('index')

cart/templates/cart/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Fripify - vente - de - friperies--chics-et-raffinés-- TG</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

	
	   <!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<!-- FontAwesome -->
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'index' %}">
								<img src="{% static 'img/logo.png' %}" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url 'index' %}">Accueil</a>
									
								</li>
								<li><a href="{% url 'onlineshop:product_list' %}">Boutique</a>
									<ul class="sub-menu">
										<li><a href="{% url 'hauts' %}">Hauts</a></li>
										<li><a href="{% url 'pantalon' %}">Pantalons</a></li>
										<li><a href="{% url 'contact' %}">t-shirt homme</a></li>
										<li><a href="{% url 'jupes' %}">Jupes</a></li>
										<li><a href="{% url 'robes' %}">Robes</a></li>
									</ul>
								</li>
								<li><a href="{% url 'contact' %}">Contact</a></li>
								<li><a href="about.html">A propos</a></li>
								
								
								
								
								<li>
									<div class="header-icons">
										<a class="shopping-cart" href="cart.html"><i class="fas fa-shopping-cart"></i></a>
										<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
									</div>
								</li>
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Fresh and Organic</p>
						<h1>Cart</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- cart -->
	<div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-remove"></th>
									<th class="product-image">Product Image</th>
									<th class="product-name">Name</th>
									<th class="product-price">Price</th>
									<th class="product-quantity">Quantity</th>				
								</tr>
							</thead>
							<tbody>
								{% for item in cart %}
        						{% with product=item.product %}
								<tr class="table-body-row">
									<td class="product-remove">
										<a href="{% url "cart:cart_remove" product.id %}"><i class="fa fa-window-close"></i></a>
										 {% comment %} <form action="{% url "cart:cart_remove" product.id %}" methode="post">
											</i><input type="submit" value="Remove">
											
											{% csrf_token %}
										</form>  {% endcomment %}
									</td>
									<td class="product-image">
										<a href="{{ product.get_absolute_url }}">
											<img src="{{ product.image.url }}">
										</a>
									</td>
									<td class="product-name">{{ product.name}}</td>
									<td class="product-price">{{ item.price}}cfa</td>
									<td class="product-quantity">
										1
									</td>
								</tr>
								{% endwith %}
    							{% endfor %}
								<tr class ="total">
									<td> Total</td>
									<td colspan ="4"></td>
									<td class="num"> {{ cart.get_total_price }}cfa</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>

				<div class="col-lg-4">
					<div class="total-section">
						<table class="total-table">
							<thead class="total-table-head">
								<tr class="table-total-row">
									<th>Total</th>
									<th>{{ cart.get_total_price }}cfa</th>
								</tr>
							</thead>
						</table>
						<div class="cart-buttons">
							<a href="{% url 'onlineshop:product_list' %}" class="boxed-btn">Retourner</a>
							<a href="{% url 'cart:checkout' %}" class="boxed-btn black">Paiement</a>
						</div>
					</div>

					{% comment %} <div class="coupon-section">
						<h3>Apply Coupon</h3>
						<div class="coupon-form-wrap">
							<form action="index.html">
								<p><input type="text" placeholder="Coupon"></p>
								<p><input type="submit" value="Apply"></p>
							</form>
						</div>
					</div> {% endcomment %}
				</div>
			</div>
		</div>
	</div>
	<!-- end cart -->

	

	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">A propos de nous</h2>
						<p>Fripify est une société nouvellement au Togo, spécialisée dans la vente de friperies (abloni) de première qualité.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Nous contacter</h2>
						<ul>
							<li>Lomé,Togo.</li>
							<li>fripifyservice@gmail.com</li>
							<li>+228 92-38-35-69</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="{% url 'index' %}">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="{% url 'contact' %}">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">S'inscrire</h2>
						<p>Recevez des messages directement sur votre portable dès qu'il y'a de nouveaux articles.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	
	
	<!-- jquery -->
	<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'js/main.js' %}"></script>


</body>
</html>