base/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('hauts/', views.hauts, name='hauts'),
    path('robes/', views.robes, name='robes'),
    path('pantalons/', views.pantalons, name='pantalon'),
    path('jupes/', views.jupes, name='jupes'),
    path('contact/', views.contact, name='contact'),
    
    
]

cart/urls.py
from django.urls import path
from . import views
app_name= 'cart'

urlpatterns= [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name= 'cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name= 'cart_remove'),
 	path('checkout/', views.CheckoutView.as_view(), name='checkout'),
	# path('checkout/', views.checkout, name='checkout'),
	path('confirmation/', views.confirmation, name='confirmation'),
	path('paysuccess/', views.paysuccess, name='paysuccess'),
 
 
]

fripeproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('onlineshop/', include('onlineshop.urls', namespace='onlineshop')),
    path('', include('base.urls')),
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/urls.py
from django.urls import path
from . import views

app_name= 'onlineshop'

urlpatterns = [
    path('product_list', views.product_list, name= 'product_list'),
    path('<slug:category_slug>/', views.product_list, name= 'product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name= 'product_detail'),
]

onlineshop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length = 200, unique = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural= 'categories'
    
    def __str__ (self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_list_by_category', args = [self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank = True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    # price = models.IntegerField()
    available = models.BooleanField(default = True)
    created= models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together= (('id', 'slug'),)
    
    def __str__ (self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_detail', args = [self.id, self.slug])

onlineshop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm
# Create your views here.

def product_list(request, category_slug= None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = products.filter(category=category)
    return render(request, 'onlineshop/product/list.html', {'category':category,'categories':categories,'products':products})

def product_detail(request, id, slug):
    product= get_object_or_404(Product,id = id, slug = slug, available = True)
    cart_product_form= CartAddProductForm()
    return render(request, 'onlineshop/product/detail.html' , {'product':product,'cart_product_form':cart_product_form})

onlineshop/templates/onlineshop/product/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Shop</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
	
	<!--PreLoader
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'index' %}">
								<img src="{% static 'img/logo.png' %}" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url 'index' %}">Accueil</a>
									
								</li>
								<li><a href="{% url 'onlineshop:product_list' %}">Boutique</a>
									<ul class="sub-menu">
										<li><a href="{% url 'hauts' %}">Hauts</a></li>
										<li><a href="{% url 'pantalon' %}">Pantalons</a></li>
										<li><a href="{% url 'contact' %}">t-shirt homme</a></li>
										<li><a href="{% url 'jupes' %}">Jupes</a></li>
										<li><a href="{% url 'robes' %}">Robes</a></li>
									</ul>
								</li>
								<li><a href="{% url 'contact' %}">Contact</a></li>
								<li><a href="about.html">A propos</a></li>
								
								
								
								
								<li>
									<div class="header-icons">
										<a class="shopping-cart" href="cart.html"><i class="fas fa-shopping-cart"></i></a>
										<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
									</div>
								</li>
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>See more Details</p>
						<h1>Single Product</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- single product -->
	<div class="single-product mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					<div class="single-product-img">
						<img src="{{ product.image.url }}" alt="">
					</div>
				</div>
				<div class="col-md-7">
					<div class="single-product-content">
						<h3>{{ product.name }}</h3>
						<p class="single-product-pricing"><span>{{product.price }}cfa</span> </p>
						<div class="single-product-form">
							<form action="{% url 'cart:cart_add' product.id %}" method="post">
								{{ cart_product_form }}
								{% csrf_token %}
								<input class="cart-btn" type="submit" value="Add to cart">
								{% comment %} <a href="{% url 'cart:cart_add' product.id %}">Add to cart</a> {% endcomment %}
							</form>
							{% comment %} <a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a> {% endcomment %}
							<p><strong>Category: </strong>{{ product.category }}</p>
							{{ product.description|linebreaks}}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end single product -->

	<!-- more products -->
	<div class="more-products mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						<h3><span class="orange-text">Related</span> Products</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="assets/img/products/product-img-1.jpg" alt=""></a>
						</div>
						<h3>Strawberry</h3>
						<p class="product-price"><span>Per Kg</span> 85$ </p>
						<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="assets/img/products/product-img-2.jpg" alt=""></a>
						</div>
						<h3>Berry</h3>
						<p class="product-price"><span>Per Kg</span> 70$ </p>
						<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 offset-lg-0 offset-md-3 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="assets/img/products/product-img-3.jpg" alt=""></a>
						</div>
						<h3>Lemon</h3>
						<p class="product-price"><span>Per Kg</span> 35$ </p>
						<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end more products -->

	

	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">A propos de nous</h2>
						<p>Fripify est une société nouvellement au Togo, spécialisée dans la vente de friperies (abloni) de première qualité.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Nous contacter</h2>
						<ul>
							<li>Lomé,Togo.</li>
							<li>fripifyservice@gmail.com</li>
							<li>+228 92-38-35-69</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="{% url 'index' %}">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="{% url 'contact' %}">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">S'inscrire</h2>
						<p>Recevez des messages directement sur votre portable dès qu'il y'a de nouveaux articles.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	
	
	<!-- jquery -->
	<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

onlineshop/templates/onlineshop/product/list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Shop</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'index' %}">
								<img src="{% static 'img/logo.png' %}" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url 'index' %}">Accueil</a>
									
								</li>
								<li><a href="{% url 'onlineshop:product_list' %}">Boutique</a>
									<ul class="sub-menu">
										<li><a href="{% url 'hauts' %}">Hauts</a></li>
										<li><a href="{% url 'pantalon' %}">Pantalons</a></li>
										<li><a href="{% url 'contact' %}">t-shirt homme</a></li>
										<li><a href="{% url 'jupes' %}">Jupes</a></li>
										<li><a href="{% url 'robes' %}">Robes</a></li>
									</ul>
								</li>
								<li><a href="{% url 'contact' %}">Contact</a></li>
								<li><a href="about.html">A propos</a></li>
								
								
								
								
								<li>
									<div class="header-icons">
										<a class="shopping-cart" href="cart.html"><i class="fas fa-shopping-cart"></i></a>
										<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
									</div>
								</li>
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Mets à jour ta garde-robe</p>
						<h1>Boutique</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- products -->
	<div class="product-section mt-150 mb-150">
		<div class="container">

			<div class="row">
                <div class="col-md-12">
                    <div class="product-filters">
                    	<ul>
							<li class="active" data-filter=".all"{% if not category %} class="selected"{% endif %}>
								tous les articles
							</li>
							{% for c in categories %}
							<li data-filter=".{{c.name}}" {% if category.slug == c.slug %}  {% endif %}>
								{{c.name}}
							</li>
							{% endfor%}  
                            
                        </ul>
						
                    </div>
                </div>
            </div>

			<div class="row product-lists">
				<div class="col-lg-4 col-md-6 text-center all">
					{% for product in products %}
						<div class="single-product-item">
							<div class="product-image">
								<a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt=""></a>
							</div>
							{% comment %} <h3>{{object.title}}</h3> {% endcomment %}
							<a href ="{{ product.get_absolute_url }}"> {{ product.name}}</a>
							<p class="product-price"><span>{{ product.price }} cfa </span> </p>
							<a href="{{ product.get_absolute_url }}" class="cart-btn"><i class="fas fa-shopping-cart"></i> </a>
						</div>
					{% endfor %}
				</div>
				{% comment %} <div class="col-lg-4 col-md-6 text-center tous">
					{% for object in ma_list %}
						<div class="single-product-item">
							<div class="product-image">
								<a href="single-product.html"><img src="{{object.image.url}}" alt=""></a>
							</div>
							<h3>{{object.title}}</h3>
							<p class="product-price"><span>Per Kg</span> {{object.price}} cfa </p>
							<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
						</div>
					{% endfor %}
				</div>
				<div class="col-lg-4 col-md-6 text-center jupes">
					{% for object in jupes_list %}
						<div class="single-product-item">
							<div class="product-image">
								<a href="single-product.html"><img src="{{object.image.url}}" alt=""></a>
							</div>
							<h3>{{object.title}}</h3>
							<p class="product-price"><span>Per Kg</span> {{object.price}} cfa </p>
							<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
						</div>
					{% endfor %}
				</div>
				<div class="col-lg-4 col-md-6 text-center robes">
					{% for object in robes_list %}
						<div class="single-product-item">
							<div class="product-image">
								<a href="single-product.html"><img src="{{object.image.url}}" alt=""></a>
							</div>
							<h3>{{object.title}}</h3>
							<p class="product-price"><span>Per Kg</span> {{object.price}} cfa </p>
							<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
						</div>
					{% endfor %}
				</div>
				<div class="col-lg-4 col-md-6 text-center hauts">
					{% for object in hauts_list %}
						<div class="single-product-item">
							<div class="product-image">
								<a href="single-product.html"><img src="{{object.image.url}}" alt=""></a>
							</div>
							<h3>{{object.title}}</h3>
							<p class="product-price"><span>Per Kg</span> {{object.price}} cfa </p>
							<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
						</div>
					{% endfor %}
				</div> {% endcomment %}
				
			</div>

			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="pagination-wrap">
						<ul>
							<li><a href="#">Prev</a></li>
							<li><a href="#">1</a></li>
							<li><a class="active" href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">Next</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end products -->

	
<!-- footer -->
<div class="footer-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="footer-box about-widget">
					<h2 class="widget-title">A propos de nous</h2>
					<p>Fripify est une société nouvellement au Togo, spécialisée dans la vente de friperies (abloni) de première qualité.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box get-in-touch">
					<h2 class="widget-title">Nous contacter</h2>
					<ul>
						<li>Lomé,Togo.</li>
						<li>fripifyservice@gmail.com</li>
						<li>+228 92-38-35-69</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box pages">
					<h2 class="widget-title">Pages</h2>
					<ul>
						<li><a href="{% url 'index' %}">Home</a></li>
						<li><a href="about.html">About</a></li>
						<li><a href="services.html">Shop</a></li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box subscribe">
					<h2 class="widget-title">S'inscrire</h2>
					<p>Recevez des messages directement sur votre portable dès qu'il y'a de nouveaux articles.</p>
					<form action="index.html">
						<input type="email" placeholder="Email">
						<button type="submit"><i class="fas fa-paper-plane"></i></button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end footer -->
	
	
	
	<!-- jquery -->
	<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>